In [43]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [44]:
class train_data:
    def __init__(self, csv, past, future) -> None:
        self.csv = csv
        self.past = past
        self.future = future
    def csv_read(self):
     df = pd.read_csv(self.csv)
     train_dates = pd.to_datetime(df['Date'])
     cols = list(df)[1:6]
     for_training = df[cols].astype(float)

     scaler = StandardScaler()
     scaler  = scaler.fit(for_training)
     scaled_for_training = scaler.transform(for_training)
     trainX = []
     trainY = []

    #  past_days = 14
    # future = 1

     for i in range(self.past, len(scaled_for_training) -self.future +1):
         trainX.append(scaled_for_training[i - self.past:i, 0:for_training.shape[1]])
         trainY.append(scaled_for_training[i + self.future - 1:i +self.future, 0])
     trainX, trainY = np.array(trainX), np.array(trainY)

    #  print('trainX shape =={}.'.format(trainX.shape))
    #  print('trainY shape == {}.'.format(trainY.shape))

     return trainX, trainY

In [45]:
# obj = train_data('A:\Academics_NEU\sem_6\TSLA.csv',13,1)

In [46]:
trainX , trainY =obj.csv_read()

In [47]:
print(trainX)

[[[-1.28332299 -1.28457122 -1.27965521 -1.28164408 -1.28164408]
  [-1.28020915 -1.28079144 -1.27492861 -1.27968617 -1.27968617]
  [-1.27990744 -1.28290576 -1.27691453 -1.280224   -1.280224  ]
  ...
  [-1.27809706 -1.28343728 -1.28175865 -1.28766892 -1.28766892]
  [-1.28874807 -1.29265053 -1.28908981 -1.29513802 -1.29513802]
  [-1.29439039 -1.28750057 -1.28943006 -1.28294935 -1.28294935]]

 [[-1.28020915 -1.28079144 -1.27492861 -1.27968617 -1.27968617]
  [-1.27990744 -1.28290576 -1.27691453 -1.280224   -1.280224  ]
  [-1.28028761 -1.28539806 -1.28612641 -1.29184461 -1.29184461]
  ...
  [-1.28874807 -1.29265053 -1.28908981 -1.29513802 -1.29513802]
  [-1.29439039 -1.28750057 -1.28943006 -1.28294935 -1.28294935]
  [-1.28530837 -1.28706353 -1.28293411 -1.28420631 -1.28420631]]

 [[-1.27990744 -1.28290576 -1.27691453 -1.280224   -1.280224  ]
  [-1.28028761 -1.28539806 -1.28612641 -1.29184461 -1.29184461]
  [-1.28946619 -1.28839827 -1.2849757  -1.28734259 -1.28734259]
  ...
  [-1.29439039 -1.